server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cqvh8c5ds78s739jh2d0-a.oregon-postgres.render.com:5432/cc_n473
    username: cc_n473_user
    password: JVFilgzn3EwMXwllHgYCdczK4bzJd6iA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587 
    username: "bandivinay24@gmail.com"
    password: "bicm nmls xdme mfzw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true    
upload-dir:
   user-file: C:\\Users\\Bandi.Vinay\\raasilabs
